MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.11.3

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,39 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "SQG5pZ5+GmRB5aiUdx8wNooDWrRbqrxcSyQPMFGq46666tbu1AKE8CNdGlz16JczCs58SJpeYySa6paoDe4A7ldsXr28slqVyiX4zc2PCmO5xVv1X9mVaaAphERhQngVv6aRaHeNEsV+dk5BGwIlbRMlzA2HtgXo2PZ5c7LsuaIZ7S3FQMdDCVrbeLR/B5VFNlw6Y6AUY5ncZsDfQsrhUjwRjXqdTLUnUa+QK+nWT9GAk3qt/Nb/wUq8N1Zr0/C2+iE9TKXq4JFwK1SKe+DhA4MD4rd8Dx/4cp8XuKTpFy8Mrc2ozG4W8Ef0zyS1Ng0d8yQyA1bA2zevQHAO0OBfrdCDTtxdx8s1+NtK9GpZN7jR6boUHR3ExOOKFyBKKRbfiW7WPxIz9BWNvdFEyXCg4fmm6Nw/pb3jErhx+0uEKFkKVDuZ6l6yg25wvFd1pZq4v+V1OcWLmcHHbAe1xPmxu4w7JIEJ1dsDrKD1oPh7IN3qI6PZoEaMvWRrLzUfhZPSiwM7iGkpJOEYNkYgdE1JUeqcsu0xChp7noaxtrVlsIRrYURkpl9PMDJFTsCWvCLUJJHjhXNARPgM/B7TvYEugpPSb1zDm36GBpZXgb4sZX2ZR6N6VYJFy/jRywCYVXQPk9Uj7g9J/9VA3BxnjQ4b5elmwNoNfEl9oGJYMI3mcLE="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
